// File generated by FlutterFire CLI & configured for ChatSpace
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChatSpaceDemoWebApiKey1234567890',
    appId: '1:100234567890:web:7894561230abc',
    messagingSenderId: '100234567890',
    projectId: 'chatspace-app',
    authDomain: 'chatspace-app.firebaseapp.com',
    storageBucket: 'chatspace-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChatSpaceDemoAndroidApiKey123456',
    appId: '1:100234567890:android:3490f8982a74c76b123456',
    messagingSenderId: '100234567890',
    projectId: 'chatspace-app',
    storageBucket: 'chatspace-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChatSpaceDemoIosApiKey1234567890',
    appId: '1:100234567890:ios:abcdef1234567890',
    messagingSenderId: '100234567890',
    projectId: 'chatspace-app',
    storageBucket: 'chatspace-app.appspot.com',
    iosBundleId: 'com.chatspace.app',
  );
}
